### ISSUE TITLE
Simplify logic for fetching tutorial images

### ISSUE THREAD

**Issue by sayanee** [hutscape/hutscape.github.io#14]
https://github.com/hutscape/hutscape.github.io/blob/b801a528d3d47cabcdd9a38bc1bd107588803b4e/_layouts/tutorials.html#L173-L188

By using individual tutorial metadata. [Example](https://github.com/hutscape/oak/blob/488a7ddef4499b3fbc736f1480942c06dfd26354/_examples/gps-pa1010d-uart.md):

```yaml
images:
  prototype: gps-pa1010d-uart-prototype.jpg
  console: gps-pa1010d-uart-console.png
  schematic: gps-pa1010d-uart-schematic.png
```

Advantages:
-  Images can also be shared among many tutorials
- No more empty `section` HTML element if no images are there for a tutorial
