### ISSUE TITLE
Add a template.md for Tutorials to refer to all the possible meta tags

### ISSUE THREAD

**Issue by sayanee** [hutscape/hutscape.github.io#18]
```yaml
---
layout: tutorials
title: Hello world ESP32-S3 with Tasmota
dependancies:
  - name: Esptool
    url: https://github.com/espressif/esptool
  - name: Tasmota flashing with estool.py
    url: https://tasmota.github.io/docs/Getting-Started/#flashing
chips:
  - ESP32-S3-WROOM-1-N8R2
dev_board: ESP32-S3-DevKitC-1
components:
  - name: ESP32-S3-DevKitC-1-N8R2
    url: https://www.aliexpress.com/item/1005003979778978.html
prerequisutes:
  - name: Blinky with Arduino on ESP32-S3
    url: blinky-arduino-esp32s3
has_code: false
images:
  prototype: hello-esp32s3-prototype.jpg
features:
  - tasmota
  - esp32s3
references:
  - name: Buy the official Espressif devkit
    url: https://www.espressif.com/en/products/devkits/esp32-devkitc/overview
  - name: Schematic of ESP32-S3-DEVKITC-1 V1
    url: https://dl.espressif.com/dl/SCH_ESP32-S3-DEVKITC-1_V1_20210312C.pdf
  - name: Pinouts
    url: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html#pin-layout
  - name: Tasmota getting started
    url: https://tasmota.github.io/docs/Getting-Started/
  - name: Error - Invalid image block, can't boot
    url: https://github.com/arendst/Tasmota/discussions/14973#discussioncomment-2251403
---
```
